spring:
  rabbitmq:
    addresses: 192.168.0.9:49156
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 500
          max-interval: 2000
          multiplier: 2
        default-requeue-rejected: false
